### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sbstp** [sbstp/nightshift#2]
- [ ] symlink support
- [ ] xattr support
- [ ] set_attr tests
- [ ] OpenFlags checking on read/write
- [ ] OpenFlags truncate/append
- [ ] Permissions/ownership checking, chmod, UID, GID, etc.
- [x] Root node should have ownership of mounted directory
- [ ] Async writes for performance
- [ ] Add `.` and `..` directory entries
- [x] Zstd compression support at block level
